converge-server/modules/converge-war/src/main/java/dk/i2m/converge/jsf/beans/ActivityStream.java
/*
 * Copyright (C) 2011 Interactive Media Management
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package dk.i2m.converge.jsf.beans;

import dk.i2m.converge.core.Notification;
import dk.i2m.converge.core.security.UserAccount;
import dk.i2m.converge.ejb.facades.UserFacadeLocal;
import dk.i2m.jsf.JsfUtils;
import javax.ejb.EJB;
import javax.faces.event.ActionEvent;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;

/**
 *
 * @author Allan Lykke Christensen
 */
public class ActivityStream {

    @EJB private UserFacadeLocal userFacade;

    private int show = BATCH_SIZE;

    private static final int BATCH_SIZE = 25;

    private DataModel notifications = null;

    private Long total = 0L;

    public DataModel getNotifications() {
        if (notifications == null) {
            notifications = new ListDataModel(userFacade.getNotifications(getUser().getUsername(), 0, show));
            total = userFacade.getNotificationCount(getUser().getUsername());
        }
        return notifications;
    }
    
    public void onDismissAll(ActionEvent event) {
        userFacade.dismiss(getUser());
        this.notifications = null;
    }
    
    public void onCheckForUpdates(ActionEvent event) {
        Long count = userFacade.getNotificationCount(getUser().getUsername());
        if (count != total) {
            this.notifications = null;
        }
    }

    public void onShowMore(ActionEvent event) {
        show += BATCH_SIZE;
        this.notifications = null;
    }

    public void setDeleteNotification(Notification notification) {
        userFacade.dismiss(notification);
        this.notifications = null;
    }
    
    public boolean isShowMore() {
        if (total > show) {
            return true;
        } else {
            return false;
        }
    }

    private UserAccount getUser() {
        final String valueExpression = "#{userSession.user}";
        return (UserAccount) JsfUtils.getValueOfValueExpression(valueExpression);
    }
}

converge-server/modules/converge-war/src/main/java/dk/i2m/converge/jsf/beans/BaseBean.java
/*
 * Copyright (C) 2010 Interactive Media Management
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package dk.i2m.converge.jsf.beans;

import dk.i2m.converge.core.DataNotFoundException;
import dk.i2m.converge.core.security.UserAccount;
import dk.i2m.converge.ejb.facades.UserFacadeLocal;
import dk.i2m.jsf.JsfUtils;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.faces.context.FacesContext;

/**
 * Base bean providing useful methods for JSF managed beans.
 *
 * @author Allan Lykke Christensen
 */
public abstract class BaseBean {

    protected static final Logger logger = Logger.getLogger(BaseBean.class.getName());

    @EJB private UserFacadeLocal userFacade;

    private UserAccount currentUserAccount;

    /**
     * Gets the current user, or {@code null} if the user is not logged in.
     *
     * @return Current user logged in.
     */
    public UserAccount getUser() {
        if (currentUserAccount == null) {
            FacesContext ctx = FacesContext.getCurrentInstance();
            String uid = ctx.getExternalContext().getRemoteUser();

            // Used by the session overview to see the name of the users logged in
            JsfUtils.getHttpSession().setAttribute("uid", uid);

            if (uid != null || !uid.isEmpty()) {
                try {
                    currentUserAccount = userFacade.findById(uid);
                } catch (DataNotFoundException ex) {
                    logger.log(Level.INFO, "User [{0}] could not be found", uid);
                }
            }

        }
        return currentUserAccount;
    }

    /**
     * Determines if the current user is in a given role.
     *
     * @param role
     *          Name of the role
     * @return <code>true</code> if the user is in the given role, otherwise
     *         <code>false</code>
     */
    public boolean isUserInRole(String role) {
        FacesContext ctx = FacesContext.getCurrentInstance();
        return ctx.getExternalContext().isUserInRole(role);
    }
}

converge-server/modules/converge-war/src/main/java/dk/i2m/converge/jsf/beans/Bundle.java
/*
 * Copyright (C) 2012 Interactive Media Management
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package dk.i2m.converge.jsf.beans;

/**
 * Identifier of {@link java.util.ResourceBundle}s available in
 * {@code FacesContext.xml}.
 *
 * @author Allan Lykke Christensen
 */
public enum Bundle {

    /**
     * Old ResourceBundle containing messages.
     *
     * @deprecated Use {@link Bundle#i18n}
     */
    msgs,
    /**
     * Old ResourceBundle containing resources.
     *
     * @deprecated Use {@link Bundle#i18n}
     */
    res,
    /**
     * ResourceBundle containing messages and resources for the web application.
     */
    i18n;
}

converge-server/modules/converge-war/src/main/java/dk/i2m/converge/jsf/beans/Common.java
/*
 * Copyright (C) 2010 - 2012 Interactive Media Management
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later 
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT 
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more 
 * details.
 *
 * You should have received a copy of the GNU General Public License along with 
 * this program. If not, see <http://www.gnu.org/licenses/>.
 */
package dk.i2m.converge.jsf.beans;

import dk.i2m.converge.core.Announcement;
import dk.i2m.converge.core.ConfigurationKey;
import dk.i2m.converge.core.calendar.EventCategory;
import dk.i2m.converge.core.content.AssignmentType;
import dk.i2m.converge.core.content.Language;
import dk.i2m.converge.core.content.NewsItemField;
import dk.i2m.converge.core.content.catalogue.Catalogue;
import dk.i2m.converge.core.content.catalogue.MediaItemStatus;
import dk.i2m.converge.core.content.catalogue.Rendition;
import dk.i2m.converge.core.content.forex.Currency;
import dk.i2m.converge.core.content.markets.FinancialMarket;
import dk.i2m.converge.core.content.weather.Location;
import dk.i2m.converge.core.content.weather.Situation;
import dk.i2m.converge.core.metadata.*;
import dk.i2m.converge.core.newswire.NewswireService;
import dk.i2m.converge.core.plugin.*;
import dk.i2m.converge.core.security.*;
import dk.i2m.converge.core.workflow.*;
import dk.i2m.converge.ejb.facades.*;
import dk.i2m.converge.ejb.services.NewswireServiceLocal;
import dk.i2m.jsf.JsfUtils;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.faces.application.Application;
import javax.faces.context.FacesContext;
import org.apache.commons.lang.StringUtils;

/**
 * JSF application bean containing common data.
 *
 * @author Allan Lykke Christensen
 */
public class Common {

    private static final Logger LOG = Logger.getLogger(Common.class.toString());

    @EJB private CalendarFacadeLocal calendarFacade;

    @EJB private UserFacadeLocal userFacade;

    @EJB private OutletFacadeLocal outletFacade;

    @EJB private SystemFacadeLocal systemFacade;

    @EJB private WorkflowFacadeLocal workflowFacade;

    @EJB private MetaDataFacadeLocal metaDataFacade;

    @EJB private NewswireServiceLocal newswireService;

    @EJB private CatalogueFacadeLocal catalogueFacade;

    @EJB private ListingFacadeLocal listingFacade;
    
    private ResourceBundle i18n = JsfUtils.getResourceBundle(Bundle.i18n.name());

    /**
     * Get the local time on the server.
     * 
     * @return Local time on the server
     */
    public Date getLocalTime() {
        return java.util.Calendar.getInstance().getTime();
    }
    
    public TimeZone getSystemTimeZone() {
        try {
            String timeZone = systemFacade.getProperty(ConfigurationKey.TIME_ZONE);
            return TimeZone.getTimeZone(timeZone);
        } catch (Exception ex) {
            LOG.log(Level.WARNING, "Could not obtain system time zone", ex.getMessage());
            return TimeZone.getDefault();
        }
    }

    /**
     * Gets the dynamic {@link UserRole}s of the system.
     *
     * @return {@link Map} of dynamic {@link UserRole}s.
     */
    public Map<String, UserRole> getUserRoles() {
        List<UserRole> original = userFacade.getUserRoles();
        Map<String, UserRole> map = new LinkedHashMap<String, UserRole>();

        for (UserRole userRole : original) {
            map.put(userRole.getName(), userRole);
        }

        return map;
    }

    /**
     * Gets a {@link Map} of {@link Outlet}s from the database.
     *
     * @return {@link Map} of {@link Outlet}s from the database.
     */
    public Map<String, Outlet> getOutlets() {
        List<Outlet> original = outletFacade.findAllOutlets();
        Map<String, Outlet> map = new LinkedHashMap<String, Outlet>();

        for (Outlet outlet : original) {
            map.put(outlet.getTitle(), outlet);
        }

        return map;
    }

    /**
     * Gets a {@link Map} of {@link Workflow}s from the database.
     *
     * @return {@link Map} of {@link Workflow}s from the database.
     */
    public Map<String, Workflow> getWorkflows() {
        List<Workflow> original = workflowFacade.findAllWorkflows();
        Map<String, Workflow> map = new LinkedHashMap<String, Workflow>();

        for (Workflow workflow : original) {
            map.put(workflow.getName(), workflow);
        }

        return map;
    }

    public Map<String, WorkflowState> getWorkflowStates() {
        List<Workflow> original = workflowFacade.findAllWorkflows();
        Map<String, WorkflowState> map = new LinkedHashMap<String, WorkflowState>();

        for (Workflow workflow : original) {
            for (WorkflowState state : workflow.getStates()) {
                map.put(workflow.getName() + " >> " + state.getName(), state);
            }
        }

        return map;
    }

    /**
     * Gets a {@link Map} of available {@link WorkflowStateType}s.
     *
     * @return {@link Map} of available {@link WorkflowStateType}s
     */
    public Map<String, WorkflowStateType> getWorkflowStateTypes() {
        Map<String, WorkflowStateType> types = new LinkedHashMap<String, WorkflowStateType>();

        for (WorkflowStateType type : WorkflowStateType.values()) {
            types.put(i18n.getString("Generic_WORKFLOW_STATE_TYPE_" + type.name()), type);
        }

        return types;
    }

    /**
     * Gets a {@link Map} of available {@link NewsItemField} user fields.
     *
     * @return {@link Map} of available {@link NewsItemField} user fields
     */
    public Map<String, NewsItemField> getNewsItemFields() {
        Map<String, NewsItemField> fields = new LinkedHashMap<String, NewsItemField>();

        for (NewsItemField field : NewsItemField.values()) {
            fields.put(i18n.getString("Generic_NEWS_ITEM_FIELD_" + field.name()), field);
        }

        return fields;
    }

    /**
     * Gets a {@link Map} of available {@link Privilege}s.
     *
     * @return {@link Map} of available {@link Privilege}s
     */
    public Map<String, Privilege> getPrivileges() {
        Map<String, Privilege> privileges = new LinkedHashMap<String, Privilege>();

        for (SystemPrivilege privilege : SystemPrivilege.values()) {
            String lbl = i18n.getString("Generic_" + privilege.getClass().getName() + "." + privilege.name());
            privileges.put(lbl, new Privilege(privilege));
        }

        return privileges;
    }

    /**
     * Gets a {@link Map} of available {@link OutletType}s.
     *
     * @return {@link Map} of available {@link OutletType}s
     */
    public Map<String, OutletType> getOutletTypes() {
        Map<String, OutletType> types = new LinkedHashMap<String, OutletType>();
        
        for (OutletType type : OutletType.values()) {
            types.put(i18n.getString("Generic_OUTLET_TYPE_" + type.name()), type);
        }

        return types;
    }

    /**
     * Gets a {@link Map} of available {@link FeeType}s.
     *
     * @return {@link Map} of available {@link FeeType}s
     */
    public Map<String, FeeType> getFeeTypes() {
        Map<String, FeeType> types = new LinkedHashMap<String, FeeType>();

        for (FeeType type : FeeType.values()) {
            types.put(i18n.getString("Generic_FEE_TYPE_" + type.name()), type);
        }

        return types;
    }

    /**
     * Gets a {@link Map} of available {@link EmploymentType}s.
     *
     * @return {@link Map} of available {@link EmploymentType}s
     */
    public Map<String, EmploymentType> getEmploymentTypes() {
        Map<String, EmploymentType> types =
                new LinkedHashMap<String, EmploymentType>();

        for (EmploymentType type : EmploymentType.values()) {
            types.put(i18n.getString("Generic_EMPLOYMENT_TYPE_" + type.name()), type);
        }

        return types;
    }

    /**
     * Gets a {@link Map} of available {@link EmploymentType}s.
     *
     * @return {@link Map} of available {@link EmploymentType}s
     */
    public Map<String, WorkflowStatePermission> getWorkflowStatePermissions() {
        Map<String, WorkflowStatePermission> types = new LinkedHashMap<String, WorkflowStatePermission>();

        for (WorkflowStatePermission permission : WorkflowStatePermission.values()) {
            types.put(i18n.getString("Generic_WORKFLOW_STATE_PERMISSION_" + permission.name()), permission);
        }

        return types;
    }

    /**
     * Gets the current year.
     *
     * @return Current year
     */
    public int getCurrentYear() {
        return java.util.Calendar.getInstance().get(java.util.Calendar.YEAR);
    }

    public Map<String, String> getHours() {
        Map<String, String> map = new LinkedHashMap<String, String>();
        for (int i = 0; i < 10; i++) {
            map.put("0" + i, "0" + i);
        }
        for (int i = 10; i < 24; i++) {
            map.put("" + i, "" + i);
        }

        return map;
    }

    public Map<String, String> getMinutes() {
        Map<String, String> map = new LinkedHashMap<String, String>();
        map.put("00", "00");
        map.put("10", "10");
        map.put("20", "20");
        map.put("30", "30");
        map.put("40", "40");
        map.put("50", "50");
        return map;
    }


converge-server/modules/converge-war/src/main/webapp/MyProfile.jspx
<?xml version="1.0" encoding="UTF-8"?>
<jsp:root version="2.0" xmlns:html="http://www.w3.org/1999/xhtml" xmlns:jsp="http://java.sun.com/JSP/Page" xmlns:c="http://java.sun.com/jstl/core" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:fn="http://java.sun.com/jsp/jstl/functions" xmlns:a4j="http://richfaces.org/a4j" xmlns:rich="http://richfaces.org/rich" xmlns:converge="http://com.interactivemediamanagement.converge/tags" xmlns:v="http://converge.i2m.dk">

    <ui:composition template="/WEB-INF/facelets/templates/myprofile.xhtml">

        <ui:define name="left">

            <h:form id="frmProfilePhoto">
                <converge:moduleHeader moduleTitle="#{i18n.MyProfile_PHOTO}" />
                <div class="moduleContent">
                    <h:panelGrid columns="2">
                        <h:graphicImage id="imgProfilePhoto" styleClass="profilePhoto"
                                        value="#{userSession.photoUrl}"
                                        alt="#{userSession.user.fullName}"
                                        title="#{userSession.user.fullName}"
                                        height="48" width="48" />

                        <rich:fileUpload listWidth="0" id="fuProfilePhoto"
                                         allowFlash="false"
                                         listHeight="0"
                                         maxFilesQuantity="1"
                                         immediateUpload="true"
                                         immediate="true"
                                         autoclear="true"
                                         fileUploadListener="#{userSession.onUploadProfilePhoto}"
                                         ajaxSingle="true"
                                         addControlLabel="#{i18n.MyProfile_CHANGE_PHOTO}">
                            <a4j:support event="onuploadcomplete"  reRender="frmProfilePhoto"/>
                        </rich:fileUpload>

                    </h:panelGrid>
                    <h:outputText value="#{i18n.MyProfile_PHOTO_SPECIFICATION}" styleClass="small"/>
                </div>
            </h:form>

            <converge:moduleSpacer />

            <converge:moduleHeader moduleTitle="#{i18n.MyProfile_DETAILS}"  />
            <div class="moduleContent">
                <h:panelGrid>
                    <h:outputText value="#{i18n.MyProfile_USERNAME}" styleClass="bold" />
                    <h:outputText value="#{userSession.user.username}" />
                    <h:outputText value="#{i18n.MyProfile_GIVEN_NAME}" styleClass="bold" />
                    <h:outputText value="#{userSession.user.givenName}" rendered="#{userSession.user.givenName != ''}" />
                    <h:outputText value="#{i18n.MyProfile_NOT_SET}" rendered="#{userSession.user.givenName == ''}" />
                    <h:outputText value="#{i18n.MyProfile_SURNAME}" styleClass="bold" />
                    <h:outputText value="#{userSession.user.surname}" rendered="#{userSession.user.surname != ''}"   />
                    <h:outputText value="#{i18n.MyProfile_NOT_SET}" rendered="#{userSession.user.surname == ''}" />
                    <h:outputText value="#{i18n.MyProfile_FULL_NAME}" styleClass="bold" />
                    <h:outputText value="#{userSession.user.fullName}" rendered="#{userSession.user.fullName != ''}"  />
                    <h:outputText value="#{i18n.MyProfile_NOT_SET}" rendered="#{userSession.user.fullName == ''}" />
                    <h:outputText value="#{i18n.MyProfile_JOB_TITLE}" styleClass="bold" />
                    <h:outputText value="#{userSession.user.jobTitle}" rendered="#{userSession.user.jobTitle != ''}" />
                    <h:outputText value="#{i18n.MyProfile_NOT_SET}" rendered="#{userSession.user.jobTitle == ''}" />
                    <h:outputText value="#{i18n.MyProfile_ORGANISATION}" styleClass="bold" />
                    <h:outputText value="#{userSession.user.organisation}" rendered="#{userSession.user.organisation != ''}" />
                    <h:outputText value="#{i18n.MyProfile_NOT_SET}" rendered="#{userSession.user.organisation == ''}" />
                    <h:outputText value="#{i18n.MyProfile_EMAIL}" styleClass="bold" />
                    <h:outputText value="#{userSession.user.email}" rendered="#{userSession.user.email != ''}" />
                    <h:outputText value="#{i18n.MyProfile_NOT_SET}" rendered="#{userSession.user.email == ''}" />
                    <h:outputText value="#{i18n.MyProfile_PHONE}" styleClass="bold" />
                    <h:outputText value="#{userSession.user.phone}" rendered="#{userSession.user.phone != ''}" />
                    <h:outputText value="#{i18n.MyProfile_NOT_SET}" rendered="#{userSession.user.phone == ''}" />
                    <h:outputText value="#{i18n.MyProfile_MOBILE}" styleClass="bold" />
                    <h:outputText value="#{userSession.user.mobile}" rendered="#{userSession.user.mobile != ''}" />
                    <h:outputText value="#{i18n.MyProfile_NOT_SET}" rendered="#{userSession.user.mobile == ''}" />
                </h:panelGrid>
            </div>

        </ui:define>

        <ui:define name="body">
            <a4j:outputPanel ajaxRendered="true">
                <v:message />
            </a4j:outputPanel>

            <h:form id="frmProfileSettings">
                <converge:moduleHeader moduleTitle="#{i18n.MyProfile_SETTINGS}"  />
                <div class="moduleContent">
                    <h:panelGrid columns="2">
                        <h:outputText value="#{i18n.MyProfile_LOCALISATION}" styleClass="bold"/>
                        <h:outputText value="&#160;" />
                        <h:outputText value="#{i18n.MyProfile_TIME_ZONE}"/>
                        <h:selectOneMenu value="#{userSession.user.timeZoneAsString}" style="width: 100%;">
                            <f:selectItems value="#{common.timeZones}" />
                        </h:selectOneMenu>

                        <h:outputText value="#{i18n.MyProfile_LANGUAGE}" />
                        <h:selectOneMenu  value="#{userSession.user.preferredLanguage}" style="width: 100%;">
                            <f:selectItems value="#{common.availableLanguages}" />
                        </h:selectOneMenu>
                        <h:outputText value="&#160;" />
                        <h:outputText value="&#160;" />
                        <h:outputText value="#{i18n.MyProfile_SEARCH_ENGINE}" styleClass="bold"/>
                        <h:outputText value="&#160;" />

                        <h:outputText value="#{i18n.MyProfile_SHOW_TAGS}"/>
                        <h:selectBooleanCheckbox value="#{userSession.user.defaultSearchEngineTags}" />

                        <h:outputText value="#{i18n.MyProfile_SEARCH_ENGINE_SORT_BY}"/>
                        <h:selectOneMenu value="#{userSession.user.defaultSearchResultsSortBy}">
                            <f:selectItem  itemLabel="#{i18n.Search_SORT_BY_SCORE}" itemValue="score" />
                            <f:selectItem  itemLabel="#{i18n.Search_SORT_BY_DATE}" itemValue="date" />
                        </h:selectOneMenu>

                        <h:outputText value="#{i18n.MyProfile_SORT_ASCENDING}"/>
                        <h:selectOneMenu id="somSearchSortOrder" value="#{userSession.user.defaultSearchResultsOrder}">
                            <f:selectItem  itemLabel="#{i18n.Search_SORT_ORDER_ASCENDING}" itemValue="true" />
                            <f:selectItem  itemLabel="#{i18n.Search_SORT_ORDER_DESCENDING}" itemValue="false" />
                        </h:selectOneMenu>

                        <h:outputText value="&#160;" />
                        <h:outputText value="&#160;" />
                        <h:outputText value="#{i18n.MyProfile_ASSIGNMENTS}" styleClass="bold"/>
                        <h:outputText value="&#160;" />
                        <h:outputText value="#{i18n.MyProfile_DEFAULT_ASSIGNMENT_TYPE}" />
                        <h:selectOneMenu id="somDefaultAssignmentType" value="#{userSession.user.defaultAssignmentType}" style="width: 100%;" converter="#{converters.enumTypeConverter}">
                            <f:selectItem itemLabel="" />
                            <f:selectItems value="#{common.assignmentTypes}" />
                        </h:selectOneMenu>

                        <h:outputText value="#{i18n.MyProfile_DEFAULT_ADD_TO_NEXT_EDITION}" />
                        <h:selectBooleanCheckbox value="#{userSession.user.defaultAddNextEdition}" />
                        
                        <h:outputText value="#{i18n.MyProfile_DEFAULT_WORK_DAY}" />
                        <rich:inputNumberSpinner value="#{userSession.user.defaultWorkDay}" enableManualInput="true" minValue="-100" maxValue="100" required="true" requiredMessage="#{i18n.MyProfile_DEFAULT_WORK_DAY_REQUIRED}" />

                        <h:outputText value="#{i18n.MyProfile_OUTLET}" />
                        <h:selectOneMenu value="#{userSession.user.defaultOutlet}" style="width: 100%;" converter="#{converters.outletConverter}">
                            <f:selectItem itemLabel="" />
                            <f:selectItems value="#{userSession.myNewsItemsOutlets}" />
                            <a4j:support event="onchange" reRender="somDefaultSection" />
                        </h:selectOneMenu>

                        <h:outputText value="#{i18n.MyProfile_SECTION}" />
                        <h:selectOneMenu id="somDefaultSection" value="#{userSession.user.defaultSection}" style="width: 100%;" converter="#{converters.sectionConverter}">
                            <f:selectItem itemLabel="" />
                            <f:selectItems value="#{userSession.myNewsItemsOutletSections}" />
                        </h:selectOneMenu>

                        <h:outputText value="#{i18n.MyProfile_DEFAULT_CATALGUE}" />
                        <h:selectOneMenu value="#{userSession.user.defaultMediaRepository}" style="width: 100%;" converter="#{converters.mediaRepositoryConverter}">
                            <f:selectItem itemLabel="" />
                            <f:selectItems value="#{userSession.myCatalogues}" />
                        </h:selectOneMenu>
                        <h:outputText value="&#160;" />
                        <h:outputText value="&#160;" />
                        <h:outputText value="&#160;" />
                        <a4j:commandButton styleClass="button dynamicButton" value="#{i18n.Generic_SAVE}" actionListener="#{userSession.onUpdateProfile}" reRender="frmPage" />
                    </h:panelGrid>
                </div>
            </h:form>

            <converge:moduleSpacer />

            <h:form id="frmPage">
                <converge:moduleHeader moduleTitle="#{i18n.MyProfile_PRIVILEGES}" />
                <div class="moduleContent">
                    <rich:dataTable id="dtPrivileges" value="#{userSession.user.userRoles}" var="userRole" width="100%" styleClass="table" headerClass="tableHeader" rowClasses="odd, even">
                        <rich:column styleClass="columnIcon center">
                            <h:graphicImage value="#{i18n.resource_ICON_USER_ROLE}" />
                        </rich:column>
                        <rich:column>
                            <f:facet name="header">
                                <h:outputText value="#{i18n.MyProfile_PRIVILEGES_ROLE}" />
                            </f:facet>
                            <h:outputText value="#{userRole.name}" />
                        </rich:column>
                        <rich:column>
                            <f:facet name="header">
                                <h:outputText value="#{i18n.MyProfile_PRIVILEGES_OUTLET}" />
                            </f:facet>
                            <rich:dataList value="#{userRole.outlets}" var="outlet">
                                <h:outputText value="#{outlet.title}" />&#160;
                            </rich:dataList>
                        </rich:column>
                    </rich:dataTable>
                </div>

            </h:form>

        </ui:define>

    </ui:composition>
</jsp:root>

converge-server/modules/converge-war/src/main/webapp/SessionExpired.jsp
<%
    response.setContentType("text/xml;charset=UTF-8");
    response.setStatus(200);
    response.sendRedirect(request.getContextPath() + "/Dashboard.xhtml");
%>

converge-server/modules/converge-war/src/main/webapp/logout.jsp
<%@page contentType="text/html" pageEncoding="utf-8"%><%
request.getSession().invalidate();
(new com.sun.appserv.security.ProgrammaticLogin()).logout(request, response, true);
response.sendRedirect(request.getContextPath());
%>