converge-server/modules/converge-war/src/main/java/dk/i2m/converge/jsf/beans/Common.java
/*
 * Copyright (C) 2010 - 2012 Interactive Media Management
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later 
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT 
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more 
 * details.
 *
 * You should have received a copy of the GNU General Public License along with 
 * this program. If not, see <http://www.gnu.org/licenses/>.
 */
package dk.i2m.converge.jsf.beans;

import dk.i2m.converge.core.Announcement;
import dk.i2m.converge.core.ConfigurationKey;
import dk.i2m.converge.core.calendar.EventCategory;
import dk.i2m.converge.core.content.AssignmentType;
import dk.i2m.converge.core.content.Language;
import dk.i2m.converge.core.content.NewsItemField;
import dk.i2m.converge.core.content.catalogue.Catalogue;
import dk.i2m.converge.core.content.catalogue.MediaItemStatus;
import dk.i2m.converge.core.content.catalogue.Rendition;
import dk.i2m.converge.core.content.forex.Currency;
import dk.i2m.converge.core.content.markets.FinancialMarket;
import dk.i2m.converge.core.content.weather.Location;
import dk.i2m.converge.core.content.weather.Situation;
import dk.i2m.converge.core.metadata.*;
import dk.i2m.converge.core.newswire.NewswireService;
import dk.i2m.converge.core.plugin.*;
import dk.i2m.converge.core.security.*;
import dk.i2m.converge.core.workflow.*;
import dk.i2m.converge.ejb.facades.*;
import dk.i2m.converge.ejb.services.NewswireServiceLocal;
import dk.i2m.jsf.JsfUtils;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.faces.application.Application;
import javax.faces.context.FacesContext;
import org.apache.commons.lang.StringUtils;

/**
 * JSF application bean containing common data.
 *
 * @author Allan Lykke Christensen
 */
public class Common {

    private static final Logger LOG = Logger.getLogger(Common.class.toString());

    @EJB private CalendarFacadeLocal calendarFacade;

    @EJB private UserFacadeLocal userFacade;

    @EJB private OutletFacadeLocal outletFacade;

    @EJB private SystemFacadeLocal systemFacade;

    @EJB private WorkflowFacadeLocal workflowFacade;

    @EJB private MetaDataFacadeLocal metaDataFacade;

    @EJB private NewswireServiceLocal newswireService;

    @EJB private CatalogueFacadeLocal catalogueFacade;

    @EJB private ListingFacadeLocal listingFacade;
    
    private ResourceBundle i18n = JsfUtils.getResourceBundle(Bundle.i18n.name());

    /**
     * Get the local time on the server.
     * 
     * @return Local time on the server
     */
    public Date getLocalTime() {
        return java.util.Calendar.getInstance().getTime();
    }
    
    public TimeZone getSystemTimeZone() {
        try {
            String timeZone = systemFacade.getProperty(ConfigurationKey.TIME_ZONE);
            return TimeZone.getTimeZone(timeZone);
        } catch (Exception ex) {
            LOG.log(Level.WARNING, "Could not obtain system time zone", ex.getMessage());
            return TimeZone.getDefault();
        }
    }

    /**
     * Gets the dynamic {@link UserRole}s of the system.
     *
     * @return {@link Map} of dynamic {@link UserRole}s.
     */
    public Map<String, UserRole> getUserRoles() {
        List<UserRole> original = userFacade.getUserRoles();
        Map<String, UserRole> map = new LinkedHashMap<String, UserRole>();

        for (UserRole userRole : original) {
            map.put(userRole.getName(), userRole);
        }

        return map;
    }

    /**
     * Gets a {@link Map} of {@link Outlet}s from the database.
     *
     * @return {@link Map} of {@link Outlet}s from the database.
     */
    public Map<String, Outlet> getOutlets() {
        List<Outlet> original = outletFacade.findAllOutlets();
        Map<String, Outlet> map = new LinkedHashMap<String, Outlet>();

        for (Outlet outlet : original) {
            map.put(outlet.getTitle(), outlet);
        }

        return map;
    }

    /**
     * Gets a {@link Map} of {@link Workflow}s from the database.
     *
     * @return {@link Map} of {@link Workflow}s from the database.
     */
    public Map<String, Workflow> getWorkflows() {
        List<Workflow> original = workflowFacade.findAllWorkflows();
        Map<String, Workflow> map = new LinkedHashMap<String, Workflow>();

        for (Workflow workflow : original) {
            map.put(workflow.getName(), workflow);
        }

        return map;
    }

    public Map<String, WorkflowState> getWorkflowStates() {
        List<Workflow> original = workflowFacade.findAllWorkflows();
        Map<String, WorkflowState> map = new LinkedHashMap<String, WorkflowState>();

        for (Workflow workflow : original) {
            for (WorkflowState state : workflow.getStates()) {
                map.put(workflow.getName() + " >> " + state.getName(), state);
            }
        }

        return map;
    }

    /**
     * Gets a {@link Map} of available {@link WorkflowStateType}s.
     *
     * @return {@link Map} of available {@link WorkflowStateType}s
     */
    public Map<String, WorkflowStateType> getWorkflowStateTypes() {
        Map<String, WorkflowStateType> types = new LinkedHashMap<String, WorkflowStateType>();

        for (WorkflowStateType type : WorkflowStateType.values()) {
            types.put(i18n.getString("Generic_WORKFLOW_STATE_TYPE_" + type.name()), type);
        }

        return types;
    }

    /**
     * Gets a {@link Map} of available {@link NewsItemField} user fields.
     *
     * @return {@link Map} of available {@link NewsItemField} user fields
     */
    public Map<String, NewsItemField> getNewsItemFields() {
        Map<String, NewsItemField> fields = new LinkedHashMap<String, NewsItemField>();

        for (NewsItemField field : NewsItemField.values()) {
            fields.put(i18n.getString("Generic_NEWS_ITEM_FIELD_" + field.name()), field);
        }

        return fields;
    }

    /**
     * Gets a {@link Map} of available {@link Privilege}s.
     *
     * @return {@link Map} of available {@link Privilege}s
     */
    public Map<String, Privilege> getPrivileges() {
        Map<String, Privilege> privileges = new LinkedHashMap<String, Privilege>();

        for (SystemPrivilege privilege : SystemPrivilege.values()) {
            String lbl = i18n.getString("Generic_" + privilege.getClass().getName() + "." + privilege.name());
            privileges.put(lbl, new Privilege(privilege));
        }

        return privileges;
    }

    /**
     * Gets a {@link Map} of available {@link OutletType}s.
     *
     * @return {@link Map} of available {@link OutletType}s
     */
    public Map<String, OutletType> getOutletTypes() {
        Map<String, OutletType> types = new LinkedHashMap<String, OutletType>();
        
        for (OutletType type : OutletType.values()) {
            types.put(i18n.getString("Generic_OUTLET_TYPE_" + type.name()), type);
        }

        return types;
    }

    /**
     * Gets a {@link Map} of available {@link FeeType}s.
     *
     * @return {@link Map} of available {@link FeeType}s
     */
    public Map<String, FeeType> getFeeTypes() {
        Map<String, FeeType> types = new LinkedHashMap<String, FeeType>();

        for (FeeType type : FeeType.values()) {
            types.put(i18n.getString("Generic_FEE_TYPE_" + type.name()), type);
        }

        return types;
    }

    /**
     * Gets a {@link Map} of available {@link EmploymentType}s.
     *
     * @return {@link Map} of available {@link EmploymentType}s
     */
    public Map<String, EmploymentType> getEmploymentTypes() {
        Map<String, EmploymentType> types =
                new LinkedHashMap<String, EmploymentType>();

        for (EmploymentType type : EmploymentType.values()) {
            types.put(i18n.getString("Generic_EMPLOYMENT_TYPE_" + type.name()), type);
        }

        return types;
    }

    /**
     * Gets a {@link Map} of available {@link EmploymentType}s.
     *
     * @return {@link Map} of available {@link EmploymentType}s
     */
    public Map<String, WorkflowStatePermission> getWorkflowStatePermissions() {
        Map<String, WorkflowStatePermission> types = new LinkedHashMap<String, WorkflowStatePermission>();

        for (WorkflowStatePermission permission : WorkflowStatePermission.values()) {
            types.put(i18n.getString("Generic_WORKFLOW_STATE_PERMISSION_" + permission.name()), permission);
        }

        return types;
    }

    /**
     * Gets the current year.
     *
     * @return Current year
     */
    public int getCurrentYear() {
        return java.util.Calendar.getInstance().get(java.util.Calendar.YEAR);
    }

    public Map<String, String> getHours() {
        Map<String, String> map = new LinkedHashMap<String, String>();
        for (int i = 0; i < 10; i++) {
            map.put("0" + i, "0" + i);
        }
        for (int i = 10; i < 24; i++) {
            map.put("" + i, "" + i);
        }

        return map;
    }

    public Map<String, String> getMinutes() {
        Map<String, String> map = new LinkedHashMap<String, String>();
        map.put("00", "00");
        map.put("10", "10");
        map.put("20", "20");
        map.put("30", "30");
        map.put("40", "40");
        map.put("50", "50");
        return map;
    }


converge-server/modules/converge-war/src/main/java/dk/i2m/converge/jsf/beans/Dashboard.java
/*
 *  Copyright (C) 2010 - 2011 Interactive Media Management
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package dk.i2m.converge.jsf.beans;

import dk.i2m.converge.core.calendar.Event;
import dk.i2m.converge.core.security.UserAccount;
import dk.i2m.converge.core.views.CurrentAssignment;
import dk.i2m.converge.ejb.facades.CalendarFacadeLocal;
import dk.i2m.converge.ejb.facades.NewsItemFacadeLocal;
import dk.i2m.jsf.JsfUtils;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;

/**
 * Backing bean for {@code /Dashboard.jspx}.
 *
 * @author Allan Lykke Christensen
 */
public class Dashboard {

    @EJB private CalendarFacadeLocal calendarFacade;

    @EJB private NewsItemFacadeLocal newsItemFacade;

    private DataModel events = null;

    private DataModel assignments = null;

    private DataModel news = null;

    /**
     * Gets the {@link DataModel} containing the user assignments.
     *
     * @return {@link DataModel} containing the user assignments
     */
    public DataModel getUserAssignments() {
        if (this.assignments == null) {
            List<CurrentAssignment> ni = newsItemFacade.findCurrentAssignments(getUserAccount().getUsername());
            this.assignments = new ListDataModel(ni);
        }

        return this.assignments;
    }

    /**
     * Gets the {@link DataModel} containing upcoming events.
     *
     * @return {@link DataModel} containing upcoming events
     */
    public DataModel getEvents() {
        if (this.events == null) {
            List<Event> upcomingEvent = calendarFacade.findUpcomingEvents(5);
            this.events = new ListDataModel(upcomingEvent);
        }
        return this.events;
    }

    private UserAccount getUserAccount() {
        final String valueExpression = "#{userSession.user}";
        return (UserAccount) JsfUtils.getValueOfValueExpression(valueExpression);
    }
}

converge-server/modules/converge-war/src/main/java/dk/i2m/converge/jsf/beans/Help.java
/*
 *  Copyright (C) 2010 Interactive Media Management
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package dk.i2m.converge.jsf.beans;

/**
 * JSF managed bean for the {@code /Help.jspx} page.
 *
 * @author Allan Lykke Christensen
 */
public class Help {

    private String title = "Getting Help";

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }
}

converge-server/modules/converge-war/src/main/java/dk/i2m/converge/web/servlets/CalendarServlet.java
/*
 *  Copyright (C) 2010 Interactive Media Management
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package dk.i2m.converge.web.servlets;

import dk.i2m.converge.ejb.facades.CalendarFacadeLocal;
import java.io.IOException;
import java.io.PrintWriter;
import javax.ejb.EJB;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * Servlet for serving the VCal version of the calendar.
 *
 * @author Allan Lykke Christensen
 */
public class CalendarServlet extends HttpServlet {

    @EJB private CalendarFacadeLocal calendarFacade;

    protected void processRequest(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        response.setContentType("text/calendar;charset=UTF-8");
        PrintWriter out = response.getWriter();
        try {
            out.println(calendarFacade.generateVCal());
        } finally {
            out.close();
        }
    }

    /** 
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request
     *          servlet request
     * @param response
     *          servlet response
     * @throws ServletException
     *          if a servlet-specific error occurs
     * @throws IOException
     *          if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        processRequest(request, response);
    }

    /** 
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request
     *          servlet request
     * @param response
     *          servlet response
     * @throws ServletException
     *          if a servlet-specific error occurs
     * @throws IOException
     *          if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        processRequest(request, response);
    }

    /** 
     * Returns a short description of the servlet.
     *
     * @return String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Serves the VCAL version of the Calendar";
    }
}

converge-server/modules/converge-war/src/main/webapp/WEB-INF/facelets/templates/administration.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:c="http://java.sun.com/jstl/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:a4j="http://richfaces.org/a4j"
      xmlns:rich="http://richfaces.org/rich"
      xmlns:converge="http://com.interactivemediamanagement.converge/tags">
    <ui:composition template="/WEB-INF/facelets/templates/default.xhtml">

        <ui:define name="title">
            <h:outputText value="#{i18n.administrator_PAGE_TITLE}" />
        </ui:define>

        <ui:define name="pageBody">
            <div id="layout2">
                <div id="leftColumn">
                    <ui:insert name="leftColumnTop" />

                    <converge:sectionMenu id="menuSubsection" rendered="#{userSession.showSectionMenu}"
                                          menuTitle="#{i18n[userSession.sectionMenu.label]}"
                                          menuItems="#{userSession.sectionMenu.children}"/>
                    
                    <converge:sectionMenu id="menuAdministration"
                                          menuTitle="#{i18n.administrator_PAGE_TITLE}"
                                          menuItems="#{userSession.administration.children}"/>

                    <ui:insert name="leftColumnBottom" />
                </div>
                <div id="rightColumn">
                    <ui:insert name="body" />
                </div>
            </div>
        </ui:define>
    </ui:composition>
</html>

converge-server/modules/converge-war/src/main/webapp/WEB-INF/facelets/templates/calendar.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:c="http://java.sun.com/jstl/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:a4j="http://richfaces.org/a4j"
      xmlns:rich="http://richfaces.org/rich"
      xmlns:converge="http://com.interactivemediamanagement.converge/tags">
    <ui:composition template="/WEB-INF/facelets/templates/default.xhtml">

        <ui:define name="title">
            <h:outputText value="#{i18n.menu_CALENDAR}" />
        </ui:define>

        <ui:define name="pageBody">
            <div id="layout2">
                <div id="leftColumn">
                    <ui:insert name="leftColumnTop" />

                    <h:form id="frmCalendar">
                        <converge:moduleHeader moduleTitle="#{i18n.Calendar_Title_CALENDAR}" />
                        <div class="moduleContent">
                            <rich:calendar id="calDate"
                                           value="#{calendar.selectedDate.time}"
                                           popup="false"
                                           timeZone="#{userSession.user.timeZone}"
                                           firstWeekDay="1"
                                           style="width: 100%">
                                <a4j:support event="onchanged" actionListener="#{calendar.onSelectDate}" reRender="frmPage" />
                            </rich:calendar>
                        </div>
                    </h:form>

                    <div style="clear: both; padding-bottom: 12px;"></div>

                    <h:form id="frmCalendarOptions">

                        <converge:moduleHeader moduleTitle="#{i18n.Calendar_OPTIONS_Title}" />
                        <div class="moduleContent">
                            <h:panelGrid columns="2">

                                <h:graphicImage value="#{i18n.resource_ICON_BULLET}" rendered="#{userSession.privileged['CALENDAR']}" />

                                <a4j:commandLink id="lnkNewEvent" reRender="frmEventDetails" actionListener="#{calendar.onNewEvent}" rendered="#{userSession.privileged['CALENDAR']}">
                                    <h:outputText value="#{i18n.Calendar_NEW_EVENT}" />
                                    <rich:componentControl for="mpEventDetails"
                                                           operation="show"
                                                           event="oncomplete" />
                                </a4j:commandLink>

                                <h:graphicImage value="#{i18n.resource_ICON_BULLET}" />

                                <a4j:commandLink reRender="dtSchedule" actionListener="#{calendar.onRefreshSchedule}">
                                    <h:outputText value="#{i18n.Calendar_REFRESH}" />
                                </a4j:commandLink>

                                <h:graphicImage value="#{i18n.resource_ICON_BULLET}" />

                                <a4j:commandLink id="lnkSubscribe" onclick="#{rich:component('mpCalendarSubscribe')}.show(); return false;">
                                    <h:outputText value="#{i18n.Calendar_VCAL_SUBSCRIBE}" />
                                </a4j:commandLink>

                                <h:graphicImage value="#{i18n.resource_ICON_BULLET}" />
                                <a4j:commandLink id="lnkShowYear" reRender="frmPage" actionListener="#{calendar.onShowYear}">
                                    <h:outputText value="#{i18n.Calendar_SHOW_YEAR}" />
                                </a4j:commandLink>

                                <h:graphicImage value="#{i18n.resource_ICON_BULLET}" />
                                <a4j:commandLink id="lnkShowMonth" reRender="frmPage" actionListener="#{calendar.onShowMonth}">
                                    <h:outputText value="#{i18n.Calendar_SHOW_MONTH}" />
                                </a4j:commandLink>

                                <h:graphicImage value="#{i18n.resource_ICON_BULLET}" />
                                <a4j:commandLink id="lnkShowWeek" reRender="frmPage" actionListener="#{calendar.onShowWeek}">
                                    <h:outputText value="#{i18n.Calendar_SHOW_WEEK}" />
                                </a4j:commandLink>

                                <h:graphicImage value="#{i18n.resource_ICON_BULLET}" />
                                <a4j:commandLink id="lnkShowDay" reRender="frmPage" actionListener="#{calendar.onShowDay}">
                                    <h:outputText value="#{i18n.Calendar_SHOW_DAY}" />
                                </a4j:commandLink>

                                <h:graphicImage value="#{i18n.resource_ICON_BULLET}" />
                                <a4j:commandLink id="lnkShowUpcoming" reRender="frmPage" actionListener="#{calendar.onShowUpcoming}">
                                    <h:outputText value="#{i18n.Calendar_SHOW_UPCOMING}" />
                                </a4j:commandLink>

                            </h:panelGrid>
                        </div>
                    </h:form>
                    <div style="clear: both; padding-bottom: 12px;"></div>

                    <ui:insert name="leftColumnBottom" />
                </div>
                <div id="rightColumn">
                    <ui:insert name="body" />
                </div>
            </div>
        </ui:define>
    </ui:composition>
</html>

converge-server/modules/converge-war/src/main/webapp/WEB-INF/facelets/templates/login.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>#{i18n.Generic_APPLICATION_TITLE} -&#160;<ui:insert name="title" /></title>
        <link rel="shortcut icon" href="#{facesContext.externalContext.request.contextPath}/favicon.ico" />
        <link href="#{facesContext.externalContext.request.contextPath}/css/template.css" rel="stylesheet" type="text/css" />
        <link href="#{facesContext.externalContext.request.contextPath}/css/login.css" rel="stylesheet" type="text/css" />
        <script type="text/javascript" src="#{facesContext.externalContext.request.contextPath}/scripts/clientrequirementscheck.js"></script>
    </head>

    <body id="login">
        <table id="body">
            <tr>
                <th class="loginHeader">
                    <img src="images/converge.gif" align="center"
                         title="#{i18n.Generic_APPLICATION_TITLE} #{i18n.LogIn_BUILD} #{common.applicationVersion}"
                         alt="#{i18n.Generic_APPLICATION_TITLE} #{i18n.LogIn_BUILD} #{common.applicationVersion}" />
                </th>
            </tr>
            <tr>
                <td class="loginBody">
                    <ui:insert name="body" />
                </td>
            </tr>

        </table>

    </body>
</html>

converge-server/modules/converge-war/src/main/webapp/WEB-INF/facelets/templates/newsreader.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:c="http://java.sun.com/jstl/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:a4j="http://richfaces.org/a4j"
      xmlns:rich="http://richfaces.org/rich"
      xmlns:v="http://converge.i2m.dk"
      xmlns:converge="http://com.interactivemediamanagement.converge/tags">
    <ui:composition template="/WEB-INF/facelets/templates/default.xhtml">

        <ui:define name="title">
            <h:outputText value="News Reader" />
        </ui:define>

        <ui:define name="pageBody">
            <div id="layout2">
                <div id="leftColumn">
                    <ui:insert name="leftColumnTop" />

                    <h:form id="frmOutlets">
                        <converge:moduleHeader moduleTitle="#{i18n.Inbox_OUTLETS}" />
                        <div class="moduleContent">
                            <h:dataTable value="#{newsReader.outlets}" var="outlet">
                                <h:column>
                                    <h:graphicImage value="#{i18n.resource_ICON_BULLET}" alt="#{outlet.title}" title="#{outlet.title}" />
                                </h:column>
                                <h:column>
                                    <a4j:commandLink reRender="frmPage, frmOutlets" styleClass="#{newsReader.selectedOutlet.id == outlet.id ? 'bold' : ''}">
                                        <f:setPropertyActionListener value="#{outlet}" target="#{newsReader.selectedOutlet}" />
                                        <h:outputText value="#{outlet.title}" />
                                    </a4j:commandLink>
                                </h:column>
                            </h:dataTable>
                        </div>
                    </h:form>
                    <div style="clear: both; padding-bottom: 12px;"></div>

                    <h:form id="frmEditionDate">
                        <converge:moduleHeader moduleTitle="Date" />
                        <div class="moduleContent">
                            <rich:calendar id="calEditionDate" value="#{newsReader.selectedDate}" popup="false" firstWeekDay="1" style="width: 100%" timeZone="#{common.systemTimeZone}">
                                <a4j:support event="onchanged" actionListener="#{newsReader.onSelectDate}" reRender="frmPage, frmEditionTime" />
                            </rich:calendar>
                        </div>
                    </h:form>
                    <div style="clear: both; padding-bottom: 12px;"></div>

                    <h:form id="frmEditionTime">
                        <converge:moduleHeader moduleTitle="Editions" />
                        <div class="moduleContent">
                            <h:dataTable value="#{newsReader.selectedEditions}" var="edition">
                                <h:column>
                                    <h:graphicImage value="#{i18n.resource_ICON_BULLET}" alt="" title="" />
                                </h:column>
                                <h:column>
                                    <a4j:commandLink reRender="frmPage, frmEditionTime" styleClass="#{(newsReader.selectedEdition != null &amp;&amp; edition.id != null &amp;&amp; newsReader.selectedEdition.id == edition.id) ? 'bold' : ''}">
                                        <f:setPropertyActionListener value="#{edition}" target="#{newsReader.selectedEdition}" />
                                        
                                        <h:outputText value="#{edition.publicationDate.time}" >
                                            <f:convertDateTime pattern="#{i18n.Generic_FORMAT_TIME}" timeZone="#{common.systemTimeZone}" />
                                        </h:outputText> #{!edition.open ? ' - Closed' :''}
                                    </a4j:commandLink>
                                </h:column>
                            </h:dataTable>
                        </div>
                    </h:form>
                    <div style="clear: both; padding-bottom: 12px;"></div>

                </div>
                <div id="rightColumn">
                    <ui:insert name="body" />
                </div>
            </div>
        </ui:define>
    </ui:composition>
</html>