converge-server/modules/converge-war/src/main/java/dk/i2m/converge/jsf/beans/ActivityStream.java
/*
 * Copyright (C) 2011 Interactive Media Management
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package dk.i2m.converge.jsf.beans;

import dk.i2m.converge.core.Notification;
import dk.i2m.converge.core.security.UserAccount;
import dk.i2m.converge.ejb.facades.UserFacadeLocal;
import dk.i2m.jsf.JsfUtils;
import javax.ejb.EJB;
import javax.faces.event.ActionEvent;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;

/**
 *
 * @author Allan Lykke Christensen
 */
public class ActivityStream {

    @EJB private UserFacadeLocal userFacade;

    private int show = BATCH_SIZE;

    private static final int BATCH_SIZE = 25;

    private DataModel notifications = null;

    private Long total = 0L;

    public DataModel getNotifications() {
        if (notifications == null) {
            notifications = new ListDataModel(userFacade.getNotifications(getUser().getUsername(), 0, show));
            total = userFacade.getNotificationCount(getUser().getUsername());
        }
        return notifications;
    }
    
    public void onDismissAll(ActionEvent event) {
        userFacade.dismiss(getUser());
        this.notifications = null;
    }
    
    public void onCheckForUpdates(ActionEvent event) {
        Long count = userFacade.getNotificationCount(getUser().getUsername());
        if (count != total) {
            this.notifications = null;
        }
    }

    public void onShowMore(ActionEvent event) {
        show += BATCH_SIZE;
        this.notifications = null;
    }

    public void setDeleteNotification(Notification notification) {
        userFacade.dismiss(notification);
        this.notifications = null;
    }
    
    public boolean isShowMore() {
        if (total > show) {
            return true;
        } else {
            return false;
        }
    }

    private UserAccount getUser() {
        final String valueExpression = "#{userSession.user}";
        return (UserAccount) JsfUtils.getValueOfValueExpression(valueExpression);
    }
}

converge-server/modules/converge-war/src/main/java/dk/i2m/converge/jsf/beans/BaseBean.java
/*
 * Copyright (C) 2010 Interactive Media Management
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package dk.i2m.converge.jsf.beans;

import dk.i2m.converge.core.DataNotFoundException;
import dk.i2m.converge.core.security.UserAccount;
import dk.i2m.converge.ejb.facades.UserFacadeLocal;
import dk.i2m.jsf.JsfUtils;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.faces.context.FacesContext;

/**
 * Base bean providing useful methods for JSF managed beans.
 *
 * @author Allan Lykke Christensen
 */
public abstract class BaseBean {

    protected static final Logger logger = Logger.getLogger(BaseBean.class.getName());

    @EJB private UserFacadeLocal userFacade;

    private UserAccount currentUserAccount;

    /**
     * Gets the current user, or {@code null} if the user is not logged in.
     *
     * @return Current user logged in.
     */
    public UserAccount getUser() {
        if (currentUserAccount == null) {
            FacesContext ctx = FacesContext.getCurrentInstance();
            String uid = ctx.getExternalContext().getRemoteUser();

            // Used by the session overview to see the name of the users logged in
            JsfUtils.getHttpSession().setAttribute("uid", uid);

            if (uid != null || !uid.isEmpty()) {
                try {
                    currentUserAccount = userFacade.findById(uid);
                } catch (DataNotFoundException ex) {
                    logger.log(Level.INFO, "User [{0}] could not be found", uid);
                }
            }

        }
        return currentUserAccount;
    }

    /**
     * Determines if the current user is in a given role.
     *
     * @param role
     *          Name of the role
     * @return <code>true</code> if the user is in the given role, otherwise
     *         <code>false</code>
     */
    public boolean isUserInRole(String role) {
        FacesContext ctx = FacesContext.getCurrentInstance();
        return ctx.getExternalContext().isUserInRole(role);
    }
}

converge-server/modules/converge-war/src/main/java/dk/i2m/converge/jsf/beans/Bundle.java
/*
 * Copyright (C) 2012 Interactive Media Management
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package dk.i2m.converge.jsf.beans;

/**
 * Identifier of {@link java.util.ResourceBundle}s available in
 * {@code FacesContext.xml}.
 *
 * @author Allan Lykke Christensen
 */
public enum Bundle {

    /**
     * Old ResourceBundle containing messages.
     *
     * @deprecated Use {@link Bundle#i18n}
     */
    msgs,
    /**
     * Old ResourceBundle containing resources.
     *
     * @deprecated Use {@link Bundle#i18n}
     */
    res,
    /**
     * ResourceBundle containing messages and resources for the web application.
     */
    i18n;
}

converge-server/modules/converge-war/src/main/java/dk/i2m/converge/jsf/beans/Common.java
/*
 * Copyright (C) 2010 - 2012 Interactive Media Management
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later 
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT 
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more 
 * details.
 *
 * You should have received a copy of the GNU General Public License along with 
 * this program. If not, see <http://www.gnu.org/licenses/>.
 */
package dk.i2m.converge.jsf.beans;

import dk.i2m.converge.core.Announcement;
import dk.i2m.converge.core.ConfigurationKey;
import dk.i2m.converge.core.calendar.EventCategory;
import dk.i2m.converge.core.content.AssignmentType;
import dk.i2m.converge.core.content.Language;
import dk.i2m.converge.core.content.NewsItemField;
import dk.i2m.converge.core.content.catalogue.Catalogue;
import dk.i2m.converge.core.content.catalogue.MediaItemStatus;
import dk.i2m.converge.core.content.catalogue.Rendition;
import dk.i2m.converge.core.content.forex.Currency;
import dk.i2m.converge.core.content.markets.FinancialMarket;
import dk.i2m.converge.core.content.weather.Location;
import dk.i2m.converge.core.content.weather.Situation;
import dk.i2m.converge.core.metadata.*;
import dk.i2m.converge.core.newswire.NewswireService;
import dk.i2m.converge.core.plugin.*;
import dk.i2m.converge.core.security.*;
import dk.i2m.converge.core.workflow.*;
import dk.i2m.converge.ejb.facades.*;
import dk.i2m.converge.ejb.services.NewswireServiceLocal;
import dk.i2m.jsf.JsfUtils;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.faces.application.Application;
import javax.faces.context.FacesContext;
import org.apache.commons.lang.StringUtils;

/**
 * JSF application bean containing common data.
 *
 * @author Allan Lykke Christensen
 */
public class Common {

    private static final Logger LOG = Logger.getLogger(Common.class.toString());

    @EJB private CalendarFacadeLocal calendarFacade;

    @EJB private UserFacadeLocal userFacade;

    @EJB private OutletFacadeLocal outletFacade;

    @EJB private SystemFacadeLocal systemFacade;

    @EJB private WorkflowFacadeLocal workflowFacade;

    @EJB private MetaDataFacadeLocal metaDataFacade;

    @EJB private NewswireServiceLocal newswireService;

    @EJB private CatalogueFacadeLocal catalogueFacade;

    @EJB private ListingFacadeLocal listingFacade;
    
    private ResourceBundle i18n = JsfUtils.getResourceBundle(Bundle.i18n.name());

    /**
     * Get the local time on the server.
     * 
     * @return Local time on the server
     */
    public Date getLocalTime() {
        return java.util.Calendar.getInstance().getTime();
    }
    
    public TimeZone getSystemTimeZone() {
        try {
            String timeZone = systemFacade.getProperty(ConfigurationKey.TIME_ZONE);
            return TimeZone.getTimeZone(timeZone);
        } catch (Exception ex) {
            LOG.log(Level.WARNING, "Could not obtain system time zone", ex.getMessage());
            return TimeZone.getDefault();
        }
    }

    /**
     * Gets the dynamic {@link UserRole}s of the system.
     *
     * @return {@link Map} of dynamic {@link UserRole}s.
     */
    public Map<String, UserRole> getUserRoles() {
        List<UserRole> original = userFacade.getUserRoles();
        Map<String, UserRole> map = new LinkedHashMap<String, UserRole>();

        for (UserRole userRole : original) {
            map.put(userRole.getName(), userRole);
        }

        return map;
    }

    /**
     * Gets a {@link Map} of {@link Outlet}s from the database.
     *
     * @return {@link Map} of {@link Outlet}s from the database.
     */
    public Map<String, Outlet> getOutlets() {
        List<Outlet> original = outletFacade.findAllOutlets();
        Map<String, Outlet> map = new LinkedHashMap<String, Outlet>();

        for (Outlet outlet : original) {
            map.put(outlet.getTitle(), outlet);
        }

        return map;
    }

    /**
     * Gets a {@link Map} of {@link Workflow}s from the database.
     *
     * @return {@link Map} of {@link Workflow}s from the database.
     */
    public Map<String, Workflow> getWorkflows() {
        List<Workflow> original = workflowFacade.findAllWorkflows();
        Map<String, Workflow> map = new LinkedHashMap<String, Workflow>();

        for (Workflow workflow : original) {
            map.put(workflow.getName(), workflow);
        }

        return map;
    }

    public Map<String, WorkflowState> getWorkflowStates() {
        List<Workflow> original = workflowFacade.findAllWorkflows();
        Map<String, WorkflowState> map = new LinkedHashMap<String, WorkflowState>();

        for (Workflow workflow : original) {
            for (WorkflowState state : workflow.getStates()) {
                map.put(workflow.getName() + " >> " + state.getName(), state);
            }
        }

        return map;
    }

    /**
     * Gets a {@link Map} of available {@link WorkflowStateType}s.
     *
     * @return {@link Map} of available {@link WorkflowStateType}s
     */
    public Map<String, WorkflowStateType> getWorkflowStateTypes() {
        Map<String, WorkflowStateType> types = new LinkedHashMap<String, WorkflowStateType>();

        for (WorkflowStateType type : WorkflowStateType.values()) {
            types.put(i18n.getString("Generic_WORKFLOW_STATE_TYPE_" + type.name()), type);
        }

        return types;
    }

    /**
     * Gets a {@link Map} of available {@link NewsItemField} user fields.
     *
     * @return {@link Map} of available {@link NewsItemField} user fields
     */
    public Map<String, NewsItemField> getNewsItemFields() {
        Map<String, NewsItemField> fields = new LinkedHashMap<String, NewsItemField>();

        for (NewsItemField field : NewsItemField.values()) {
            fields.put(i18n.getString("Generic_NEWS_ITEM_FIELD_" + field.name()), field);
        }

        return fields;
    }

    /**
     * Gets a {@link Map} of available {@link Privilege}s.
     *
     * @return {@link Map} of available {@link Privilege}s
     */
    public Map<String, Privilege> getPrivileges() {
        Map<String, Privilege> privileges = new LinkedHashMap<String, Privilege>();

        for (SystemPrivilege privilege : SystemPrivilege.values()) {
            String lbl = i18n.getString("Generic_" + privilege.getClass().getName() + "." + privilege.name());
            privileges.put(lbl, new Privilege(privilege));
        }

        return privileges;
    }

    /**
     * Gets a {@link Map} of available {@link OutletType}s.
     *
     * @return {@link Map} of available {@link OutletType}s
     */
    public Map<String, OutletType> getOutletTypes() {
        Map<String, OutletType> types = new LinkedHashMap<String, OutletType>();
        
        for (OutletType type : OutletType.values()) {
            types.put(i18n.getString("Generic_OUTLET_TYPE_" + type.name()), type);
        }

        return types;
    }

    /**
     * Gets a {@link Map} of available {@link FeeType}s.
     *
     * @return {@link Map} of available {@link FeeType}s
     */
    public Map<String, FeeType> getFeeTypes() {
        Map<String, FeeType> types = new LinkedHashMap<String, FeeType>();

        for (FeeType type : FeeType.values()) {
            types.put(i18n.getString("Generic_FEE_TYPE_" + type.name()), type);
        }

        return types;
    }

    /**
     * Gets a {@link Map} of available {@link EmploymentType}s.
     *
     * @return {@link Map} of available {@link EmploymentType}s
     */
    public Map<String, EmploymentType> getEmploymentTypes() {
        Map<String, EmploymentType> types =
                new LinkedHashMap<String, EmploymentType>();

        for (EmploymentType type : EmploymentType.values()) {
            types.put(i18n.getString("Generic_EMPLOYMENT_TYPE_" + type.name()), type);
        }

        return types;
    }

    /**
     * Gets a {@link Map} of available {@link EmploymentType}s.
     *
     * @return {@link Map} of available {@link EmploymentType}s
     */
    public Map<String, WorkflowStatePermission> getWorkflowStatePermissions() {
        Map<String, WorkflowStatePermission> types = new LinkedHashMap<String, WorkflowStatePermission>();

        for (WorkflowStatePermission permission : WorkflowStatePermission.values()) {
            types.put(i18n.getString("Generic_WORKFLOW_STATE_PERMISSION_" + permission.name()), permission);
        }

        return types;
    }

    /**
     * Gets the current year.
     *
     * @return Current year
     */
    public int getCurrentYear() {
        return java.util.Calendar.getInstance().get(java.util.Calendar.YEAR);
    }

    public Map<String, String> getHours() {
        Map<String, String> map = new LinkedHashMap<String, String>();
        for (int i = 0; i < 10; i++) {
            map.put("0" + i, "0" + i);
        }
        for (int i = 10; i < 24; i++) {
            map.put("" + i, "" + i);
        }

        return map;
    }

    public Map<String, String> getMinutes() {
        Map<String, String> map = new LinkedHashMap<String, String>();
        map.put("00", "00");
        map.put("10", "10");
        map.put("20", "20");
        map.put("30", "30");
        map.put("40", "40");
        map.put("50", "50");
        return map;
    }


converge-server/modules/converge-war/src/main/webapp/WEB-INF/facelets/taglib/converge/activityStreamModule.xhtml
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:c="http://java.sun.com/jstl/core" xmlns:a4j="http://richfaces.org/a4j" xmlns:rich="http://richfaces.org/rich" xmlns:converge="http://com.interactivemediamanagement.converge/tags">
    <h:form id="frmActivityStream">
        <converge:moduleHeader moduleTitle="#{i18n.activityStreamModule_TITLE}" />
        <div class="moduleContent">
            <a4j:poll actionListener="#{activityStream.onCheckForUpdates}" ajaxSingle="true" reRender="activityStream" interval="60000" />
            <a4j:outputPanel id="activityStream" ajaxRendered="true">
                <rich:dataTable id="dtNotifications" value="#{activityStream.notifications}" var="notification" styleClass="activityStream">
                    <rich:column width="50" styleClass="activityStreamSender">
                        <h:graphicImage styleClass="profilePhoto" value="/UserPhoto?uid=#{notification.sender.id}" alt="#{notification.sender.fullName}" title="#{notification.sender.fullName}" height="48" width="48" />
                    </rich:column>
                    <rich:column styleClass="activityStreamMessage">
                        <h:panelGrid>
                            <h:outputLink value="#{notification.link}" styleClass="activityStreamSenderName">
                                <h:outputText value="#{notification.sender.fullName}" escape="false"  />
                            </h:outputLink>
                            <h:outputText value="#{notification.message}" styleClass="activityStreamMessageText" escape="false" />
                            <h:panelGroup layout="block">
                                <h:outputText value="#{notification.added.time}" styleClass="activityStreamTime">
                                    <f:converter converterId="com.ocpsoft.PrettyTimeConverter"/>
                                </h:outputText>
                                <h:outputText value="#{i18n.activityStreamModule_SEPARATOR}" escape="false" styleClass="activityStreamSeparator" rendered="#{notification.linkSet}" />
                                <h:outputLink value="#{facesContext.externalContext.request.contextPath}/#{notification.link}" styleClass="activityStreamLink" rendered="#{notification.linkSet}">
                                    <h:outputText value="#{i18n.activityStreamModule_LINK}" escape="false" />
                                </h:outputLink>
                                <h:outputText value="#{i18n.activityStreamModule_SEPARATOR}" escape="false" styleClass="activityStreamSeparator" />
                                <a4j:commandLink ajaxSingle="true" reRender="dtNotifications" styleClass="activityStreamLink">
                                    <f:setPropertyActionListener target="#{activityStream.deleteNotification}" value="#{notification}" />
                                    <h:outputText value="#{i18n.activityStreamModule_DISMISS}" escape="false" />
                                </a4j:commandLink>
                                <h:outputText value="#{i18n.activityStreamModule_SEPARATOR}" escape="false" styleClass="activityStreamSeparator" rendered="#{notification.linkSet}" />
                                <a4j:commandLink styleClass="activityStreamLink" rendered="#{notification.linkSet}" oncomplete="window.location='#{facesContext.externalContext.request.contextPath}/#{notification.link}'">
                                    <f:setPropertyActionListener target="#{activityStream.deleteNotification}" value="#{notification}" />
                                    <h:outputText value="#{i18n.activityStreamModule_LINK_AND_DISMISS}" escape="false" />
                                </a4j:commandLink>
                            </h:panelGroup>
                        </h:panelGrid>
                    </rich:column>
                </rich:dataTable>                    
                <h:panelGroup layout="block">
                    <a4j:commandLink styleClass="activityStreamBottomLink" actionListener="#{activityStream.onShowMore}" reRender="dtNotifications" value="#{i18n.activityStreamModule_SHOW_MORE}" rendered="#{activityStream.showMore}" />
                    <a4j:commandLink styleClass="activityStreamBottomLink" actionListener="#{activityStream.onDismissAll}" reRender="dtNotifications" value="#{i18n.activityStreamModule_DISMISS_ALL}" rendered="#{activityStream.notifications.rowCount &gt; 0}" />
                </h:panelGroup>
            </a4j:outputPanel>

        </div>
        <h:outputText value="#{i18n.Generic_LICENSE}" style="color: white; background: white;" />
    </h:form>
    <converge:moduleSpacer />
</ui:composition>

converge-server/modules/converge-war/src/main/webapp/WEB-INF/facelets/taglib/converge/moduleSpacer.xhtml
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:c="http://java.sun.com/jstl/core" xmlns:a4j="http://richfaces.org/a4j" xmlns:rich="http://richfaces.org/rich" xmlns:converge="http://com.interactivemediamanagement.converge/tags">

    <div style="clear: both; padding-bottom: 12px;"></div>

</ui:composition>

converge-server/modules/converge-war/src/main/webapp/WEB-INF/facelets/taglib/converge/newsItemModuleBriefing.xhtml
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:c="http://java.sun.com/jstl/core" xmlns:a4j="http://richfaces.org/a4j" xmlns:rich="http://richfaces.org/rich" xmlns:converge="http://com.interactivemediamanagement.converge/tags">

    <c:if test="#{value.assignmentBriefing != ''}">
        <converge:moduleHeader moduleTitle="#{msgs.planning_ASSIGNMENT_BRIEFING}" />
        <div class="moduleContent">
            <h:panelGrid>
                <h:outputText value="Assigned by #{value.assignedBy.fullName}" escape="false" rendered="#{value.assignedBy != null}" style="font-style: italic" />
                <h:column>
                    <h:outputText value="Deadline "  />
                    <h:outputText value="#{value.deadline.time}" style="font-weight: bold;">
                        <f:convertDateTime pattern="#{msgs.FORMAT_DATE_AND_TIME}" timeZone="#{userSession.user.timeZone}" />
                    </h:outputText>
                </h:column>
                <h:outputText value="&#160;" />
                <h:outputText value="#{value.assignmentBriefing}" escape="false" />
            </h:panelGrid>
        </div>
        <div style="clear: both; padding-bottom: 12px;"></div>
    </c:if>

</ui:composition>

converge-server/modules/converge-war/src/main/webapp/WEB-INF/facelets/taglib/converge/newsItemModulePlacement.xhtml
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:c="http://java.sun.com/jstl/core" xmlns:a4j="http://richfaces.org/a4j" xmlns:rich="http://richfaces.org/rich" xmlns:converge="http://com.interactivemediamanagement.converge/tags">

    <c:if test="#{newsItem.fieldVisible['PLACEMENT']}">

        <converge:moduleHeader moduleTitle="#{msgs.newsitem_PLACEMENT}" />
        <div>
            <h:panelGrid style="width: 98%; margin-left: 1%; margin-right: 1%;" rowClasses="left, right">
                <rich:dataTable id="dtPlacements" value="#{newsItem.selectedNewsItem.placements}" var="placement" styleClass="table" headerClass="tableHeader" rowClasses="odd, even">

                    <rich:column styleClass="columnIcon center">
                        <f:facet name="header"></f:facet>
                        <h:graphicImage value="#{res.EDITION_OPEN_ICON}" title="#{msgs.EDITION_OPEN}" alt="#{msgs.EDITION_OPEN}" rendered="#{placement.edition.open}"  />
                        <h:graphicImage value="#{res.EDITION_CLOSED_ICON}" title="#{msgs.EDITION_CLOSED}" alt="#{msgs.EDITION_CLOSED}" rendered="#{!placement.edition.open}"  />
                    </rich:column>

                    <rich:column sortBy="#{placement.outlet.title}">
                        <f:facet name="header">
                            <h:outputText value="#{msgs.OUTLET}" />
                        </f:facet>
                        <h:outputText value="#{placement.outlet.title}" />
                    </rich:column>

                    <rich:column styleClass="columnDate left" sortBy="#{placement.edition.publicationDate}">
                        <f:facet name="header">
                            <h:outputText value="#{msgs.DATE_DAY}" />
                        </f:facet>
                        <h:outputText value="#{placement.edition.publicationDate.time}">
                            <f:convertDateTime timeZone="#{common.systemTimeZone}" pattern="EEEE" />
                        </h:outputText>
                    </rich:column>

                    <rich:column styleClass="columnDate left" sortBy="#{placement.edition.publicationDate}" sortOrder="ASCENDING">
                        <f:facet name="header">
                            <h:outputText value="#{msgs.DATE}" />
                        </f:facet>
                        <h:outputText value="#{placement.edition.publicationDate.time}">
                            <f:convertDateTime timeZone="#{common.systemTimeZone}" pattern="#{msgs.FORMAT_SHORT_DATE}" />
                        </h:outputText>
                    </rich:column>

                    <rich:column styleClass="columnDate left" sortBy="#{placement.edition.publicationDate}">
                        <f:facet name="header">
                            <h:outputText value="#{msgs.TIME}" />
                        </f:facet>
                        <h:outputText value="#{placement.edition.publicationDate.time}">
                            <f:convertDateTime timeZone="#{common.systemTimeZone}" pattern="#{msgs.FORMAT_SHORT_TIME}" />
                        </h:outputText>
                    </rich:column>

                    <rich:column styleClass="left" sortBy="#{placement.section.name}">
                        <f:facet name="header">
                            <h:outputText value="#{msgs.newsitem_SECTION}" />
                        </f:facet>
                        <h:outputText value="#{placement.section.name}" title="#{placement.section.fullName}" />
                    </rich:column>

                    <rich:column styleClass="columnMediumNumber right" sortBy="#{placement.start}">
                        <f:facet name="header">
                            <h:outputText value="#{msgs.newsitem_START}" />
                        </f:facet>
                        <h:outputText value="#{placement.start}" />
                    </rich:column>

                    <rich:column styleClass="columnMediumNumber right" sortBy="#{placement.position}">
                        <f:facet name="header">
                            <h:outputText value="#{msgs.newsitem_POSITION}" />
                        </f:facet>
                        <h:outputText value="#{placement.position}" />
                    </rich:column>

                    <rich:column styleClass="columnOneButton center">
                        <f:facet name="header">
                            <a4j:commandButton styleClass="button smallButton" value="#{msgs.OUTLET_PLACEMENT_CHOOSE}" ajaxSingle="true" reRender="frmPlacementDialog" actionListener="#{newsItem.onNewPlacement}" oncomplete="#{rich:component('mpPlacement')}.show();"
                                               rendered="#{value.currentActor &amp;&amp; !value.readOnly}" />
                        </f:facet>
                        <a4j:commandButton styleClass="button smallButton" value="#{msgs.MODIFY}" ajaxSingle="true" reRender="frmPlacementDialog" oncomplete="#{rich:component('mpPlacement')}.show();"
                                           rendered="#{value.currentActor &amp;&amp; !value.readOnly}">
                            <f:setPropertyActionListener target="#{newsItem.selectedNewsItemPlacement}" value="#{placement}" />
                            <f:setPropertyActionListener target="#{newsItem.editionDate}" value="#{placement.edition.publicationDate.time}" />
                        </a4j:commandButton>
                    </rich:column>
                </rich:dataTable>
            </h:panelGrid>
        </div>
        <div style="clear: both; padding-bottom: 12px;"></div>
    </c:if>

</ui:composition>